// ============================================================
// Entity Schema Config – Example configs cho Metadata Engine
// User, Order, OrderItem, Category (self-relation)
// Đây là hard-coded config; auto-generated schema sẽ merge với config này
// ============================================================

import type { EntitySchema, SchemaRegistry } from '../core/metadata/schema.types';

// ─── Users ───────────────────────────────────────────────────
export const UsersSchema: EntitySchema = {
  name: 'users',
  label: 'Users',
  icon: '👤',
  primaryKey: 'id',
  displayField: 'username',
  description: 'System users management',
  fields: [
    {
      name: 'id',
      label: 'ID',
      type: 'number',
      isPrimary: true,
      sortable: true,
      editable: false,
      visibleInTable: true,
      visibleInCreate: false,
      visibleInEdit: false,
      width: 60,
    },
    {
      name: 'username',
      label: 'Username',
      type: 'text',
      sortable: true,
      filterable: true,
      editable: true,
      visibleInTable: true,
      visibleInCreate: true,
      visibleInEdit: true,
      placeholder: 'Enter username',
      validation: {
        required: true,
        minLength: 3,
        maxLength: 50,
        pattern: '^[a-zA-Z0-9_]+$',
        messages: {
          required: 'Username is required',
          minLength: 'Username must be at least 3 characters',
          pattern: 'Only letters, numbers and underscore allowed',
        },
      },
    },
    {
      name: 'email',
      label: 'Email',
      type: 'email',
      sortable: true,
      filterable: true,
      editable: true,
      visibleInTable: true,
      visibleInCreate: true,
      visibleInEdit: true,
      placeholder: 'user@example.com',
      validation: {
        required: true,
        email: true,
        messages: { required: 'Email is required', email: 'Invalid email format' },
      },
    },
    {
      name: 'password',
      label: 'Password',
      type: 'password',
      sortable: false,
      filterable: false,
      editable: true,
      visibleInTable: false,
      visibleInCreate: true,
      visibleInEdit: false,
      placeholder: '••••••••',
      validation: {
        required: true,
        minLength: 6,
        messages: {
          required: 'Password is required',
          minLength: 'Password must be at least 6 characters',
        },
      },
    },
    {
      name: 'role',
      label: 'Role',
      type: 'select',
      sortable: true,
      filterable: true,
      editable: true,
      visibleInTable: true,
      visibleInCreate: true,
      visibleInEdit: true,
      defaultValue: 'user',
      options: [
        { label: 'Admin', value: 'admin' },
        { label: 'User', value: 'user' },
        { label: 'Viewer', value: 'viewer' },
      ],
      validation: { required: true, messages: { required: 'Role is required' } },
    },
    {
      name: 'is_active',
      label: 'Active',
      type: 'boolean',
      sortable: true,
      filterable: true,
      editable: true,
      visibleInTable: true,
      visibleInCreate: true,
      visibleInEdit: true,
      defaultValue: true,
    },
    {
      name: 'created_at',
      label: 'Created At',
      type: 'datetime',
      sortable: true,
      filterable: true,
      editable: false,
      visibleInTable: true,
      visibleInCreate: false,
      visibleInEdit: false,
    },
  ],
  permissions: { read: true, create: true, update: true, delete: true, export: true },
  defaultSort: { field: 'created_at', direction: 'desc' },
  defaultPageSize: 20,
  pageSizes: [10, 20, 50, 100],
};

// ─── Orders ──────────────────────────────────────────────────
export const OrdersSchema: EntitySchema = {
  name: 'orders',
  label: 'Orders',
  icon: '📦',
  primaryKey: 'id',
  displayField: 'id',
  description: 'Customer orders management',
  fields: [
    {
      name: 'id',
      label: 'ID',
      type: 'number',
      isPrimary: true,
      sortable: true,
      editable: false,
      visibleInTable: true,
      visibleInCreate: false,
      visibleInEdit: false,
      width: 60,
    },
    {
      name: 'order_number',
      label: 'Order Number',
      type: 'text',
      sortable: true,
      filterable: true,
      editable: false,
      visibleInTable: true,
      visibleInCreate: false,
      visibleInEdit: false,
    },
    {
      name: 'user_id',
      label: 'Customer',
      type: 'relation',
      sortable: true,
      filterable: true,
      editable: true,
      visibleInTable: true,
      visibleInCreate: true,
      visibleInEdit: true,
      relation: {
        type: 'ManyToOne',
        target: 'users',
        displayField: 'username',
        foreignKey: 'user_id',
        searchField: 'username',
      },
      validation: { required: true, messages: { required: 'Customer is required' } },
    },
    {
      name: 'total',
      label: 'Total Amount',
      type: 'number',
      sortable: true,
      filterable: true,
      editable: true,
      visibleInTable: true,
      visibleInCreate: true,
      visibleInEdit: true,
      validation: {
        required: true,
        min: 0,
        messages: { required: 'Total is required', min: 'Total must be >= 0' },
      },
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      sortable: true,
      filterable: true,
      editable: true,
      visibleInTable: true,
      visibleInCreate: true,
      visibleInEdit: true,
      defaultValue: 'pending',
      options: [
        { label: 'Pending', value: 'pending' },
        { label: 'Processing', value: 'processing' },
        { label: 'Shipped', value: 'shipped' },
        { label: 'Delivered', value: 'delivered' },
        { label: 'Cancelled', value: 'cancelled' },
      ],
      validation: { required: true },
    },
    {
      name: 'notes',
      label: 'Notes',
      type: 'textarea',
      sortable: false,
      filterable: false,
      editable: true,
      visibleInTable: false,
      visibleInCreate: true,
      visibleInEdit: true,
      placeholder: 'Additional order notes...',
    },
    {
      name: 'items',
      label: 'Order Items',
      type: 'relation',
      sortable: false,
      filterable: false,
      editable: false,
      visibleInTable: false,
      visibleInCreate: false,
      visibleInEdit: true,
      relation: {
        type: 'OneToMany',
        target: 'order_items',
        displayField: 'product_name',
        foreignKey: 'order_id',
      },
    },
    {
      name: 'created_at',
      label: 'Created At',
      type: 'datetime',
      sortable: true,
      filterable: true,
      editable: false,
      visibleInTable: true,
      visibleInCreate: false,
      visibleInEdit: false,
    },
  ],
  permissions: { read: true, create: true, update: true, delete: true, export: true },
  defaultSort: { field: 'created_at', direction: 'desc' },
  defaultPageSize: 20,
};

// ─── Order Items ─────────────────────────────────────────────
export const OrderItemsSchema: EntitySchema = {
  name: 'order_items',
  label: 'Order Items',
  icon: '🛒',
  primaryKey: 'id',
  displayField: 'product_name',
  fields: [
    {
      name: 'id',
      label: 'ID',
      type: 'number',
      isPrimary: true,
      sortable: true,
      editable: false,
      visibleInTable: true,
      visibleInCreate: false,
      visibleInEdit: false,
      width: 60,
    },
    {
      name: 'order_id',
      label: 'Order',
      type: 'relation',
      sortable: true,
      filterable: true,
      editable: true,
      visibleInTable: true,
      visibleInCreate: true,
      visibleInEdit: false,
      relation: {
        type: 'ManyToOne',
        target: 'orders',
        displayField: 'order_number',
        foreignKey: 'order_id',
      },
      validation: { required: true },
    },
    {
      name: 'product_name',
      label: 'Product Name',
      type: 'text',
      sortable: true,
      filterable: true,
      editable: true,
      visibleInTable: true,
      visibleInCreate: true,
      visibleInEdit: true,
      validation: { required: true, maxLength: 200 },
    },
    {
      name: 'quantity',
      label: 'Quantity',
      type: 'number',
      sortable: true,
      filterable: true,
      editable: true,
      visibleInTable: true,
      visibleInCreate: true,
      visibleInEdit: true,
      defaultValue: 1,
      validation: { required: true, min: 1, messages: { min: 'Quantity must be at least 1' } },
    },
    {
      name: 'unit_price',
      label: 'Unit Price',
      type: 'number',
      sortable: true,
      filterable: true,
      editable: true,
      visibleInTable: true,
      visibleInCreate: true,
      visibleInEdit: true,
      validation: { required: true, min: 0 },
    },
    {
      name: 'subtotal',
      label: 'Subtotal',
      type: 'number',
      sortable: true,
      filterable: false,
      editable: false,
      visibleInTable: true,
      visibleInCreate: false,
      visibleInEdit: false,
    },
  ],
  permissions: { read: true, create: true, update: true, delete: true },
  defaultSort: { field: 'id', direction: 'asc' },
};

// ─── Categories (Self-Relation) ──────────────────────────────
export const CategoriesSchema: EntitySchema = {
  name: 'categories',
  label: 'Categories',
  icon: '📁',
  primaryKey: 'id',
  displayField: 'name',
  description: 'Category tree with self-relation (parent-child)',
  fields: [
    {
      name: 'id',
      label: 'ID',
      type: 'number',
      isPrimary: true,
      sortable: true,
      editable: false,
      visibleInTable: true,
      visibleInCreate: false,
      visibleInEdit: false,
      width: 60,
    },
    {
      name: 'name',
      label: 'Category Name',
      type: 'text',
      sortable: true,
      filterable: true,
      editable: true,
      visibleInTable: true,
      visibleInCreate: true,
      visibleInEdit: true,
      validation: {
        required: true,
        minLength: 2,
        maxLength: 100,
        messages: { required: 'Category name is required' },
      },
    },
    {
      name: 'slug',
      label: 'Slug',
      type: 'text',
      sortable: true,
      filterable: true,
      editable: true,
      visibleInTable: true,
      visibleInCreate: true,
      visibleInEdit: true,
      placeholder: 'auto-generated-slug',
      validation: {
        pattern: '^[a-z0-9-]+$',
        messages: { pattern: 'Slug must be lowercase letters, numbers and hyphens only' },
      },
    },
    {
      name: 'parent_id',
      label: 'Parent Category',
      type: 'relation',
      sortable: true,
      filterable: true,
      editable: true,
      visibleInTable: true,
      visibleInCreate: true,
      visibleInEdit: true,
      relation: {
        type: 'ManyToOne',
        target: 'categories', // Self-relation!
        displayField: 'name',
        foreignKey: 'parent_id',
        searchField: 'name',
      },
    },
    {
      name: 'children',
      label: 'Sub-categories',
      type: 'relation',
      sortable: false,
      filterable: false,
      editable: false,
      visibleInTable: false,
      visibleInCreate: false,
      visibleInEdit: true,
      relation: {
        type: 'OneToMany',
        target: 'categories', // Self-relation!
        displayField: 'name',
        foreignKey: 'parent_id',
      },
    },
    {
      name: 'description',
      label: 'Description',
      type: 'textarea',
      sortable: false,
      filterable: false,
      editable: true,
      visibleInTable: false,
      visibleInCreate: true,
      visibleInEdit: true,
    },
    {
      name: 'is_active',
      label: 'Active',
      type: 'boolean',
      sortable: true,
      filterable: true,
      editable: true,
      visibleInTable: true,
      visibleInCreate: true,
      visibleInEdit: true,
      defaultValue: true,
    },
    {
      name: 'sort_order',
      label: 'Sort Order',
      type: 'number',
      sortable: true,
      filterable: false,
      editable: true,
      visibleInTable: true,
      visibleInCreate: true,
      visibleInEdit: true,
      defaultValue: 0,
      validation: { min: 0 },
    },
  ],
  permissions: { read: true, create: true, update: true, delete: true },
  defaultSort: { field: 'sort_order', direction: 'asc' },
  defaultPageSize: 50,
};

// ─── Products (example with many field types) ────────────────
export const ProductsSchema: EntitySchema = {
  name: 'products',
  label: 'Products',
  icon: '🏷️',
  primaryKey: 'id',
  displayField: 'name',
  description: 'Product catalog with multiple field type examples',
  fields: [
    {
      name: 'id',
      label: 'ID',
      type: 'number',
      isPrimary: true,
      sortable: true,
      editable: false,
      visibleInTable: true,
      visibleInCreate: false,
      visibleInEdit: false,
      width: 60,
    },
    {
      name: 'name',
      label: 'Product Name',
      type: 'text',
      sortable: true,
      filterable: true,
      editable: true,
      visibleInTable: true,
      visibleInCreate: true,
      visibleInEdit: true,
      validation: { required: true, minLength: 2, maxLength: 200 },
    },
    {
      name: 'description',
      label: 'Description',
      type: 'textarea',
      sortable: false,
      filterable: false,
      editable: true,
      visibleInTable: false,
      visibleInCreate: true,
      visibleInEdit: true,
    },
    {
      name: 'price',
      label: 'Price',
      type: 'number',
      sortable: true,
      filterable: true,
      editable: true,
      visibleInTable: true,
      visibleInCreate: true,
      visibleInEdit: true,
      validation: { required: true, min: 0, messages: { min: 'Price must be >= 0' } },
    },
    {
      name: 'category_id',
      label: 'Category',
      type: 'relation',
      sortable: true,
      filterable: true,
      editable: true,
      visibleInTable: true,
      visibleInCreate: true,
      visibleInEdit: true,
      relation: {
        type: 'ManyToOne',
        target: 'categories',
        displayField: 'name',
        foreignKey: 'category_id',
      },
      validation: { required: true },
    },
    {
      name: 'tags',
      label: 'Tags',
      type: 'multiselect',
      sortable: false,
      filterable: true,
      editable: true,
      visibleInTable: true,
      visibleInCreate: true,
      visibleInEdit: true,
      options: [
        { label: 'Featured', value: 'featured' },
        { label: 'New', value: 'new' },
        { label: 'Sale', value: 'sale' },
        { label: 'Best Seller', value: 'best-seller' },
      ],
    },
    {
      name: 'website',
      label: 'Website',
      type: 'url',
      sortable: false,
      filterable: false,
      editable: true,
      visibleInTable: true,
      visibleInCreate: true,
      visibleInEdit: true,
      placeholder: 'https://example.com',
      validation: { url: true },
    },
    {
      name: 'metadata',
      label: 'Metadata (JSON)',
      type: 'json',
      sortable: false,
      filterable: false,
      editable: true,
      visibleInTable: false,
      visibleInCreate: true,
      visibleInEdit: true,
      placeholder: '{ "weight": "1kg", "color": "red" }',
      helpText: 'Additional product data in JSON format',
    },
    {
      name: 'is_active',
      label: 'Active',
      type: 'boolean',
      sortable: true,
      filterable: true,
      editable: true,
      visibleInTable: true,
      visibleInCreate: true,
      visibleInEdit: true,
      defaultValue: true,
    },
    {
      name: 'created_at',
      label: 'Created',
      type: 'datetime',
      sortable: true,
      filterable: true,
      editable: false,
      visibleInTable: true,
      visibleInCreate: false,
      visibleInEdit: false,
    },
  ],
  permissions: { read: true, create: true, update: true, delete: true, export: true },
  defaultSort: { field: 'created_at', direction: 'desc' },
  defaultPageSize: 20,
};

// ─── Schema Registry ─────────────────────────────────────────
/** All registered entity schemas – lookup by name */
export const schemaRegistry: SchemaRegistry = {
  users: UsersSchema,
  orders: OrdersSchema,
  order_items: OrderItemsSchema,
  categories: CategoriesSchema,
  products: ProductsSchema,
};
