#!/usr/bin/env node

// ============================================================
// CLI Generator – Generate module files from EntitySchema config
// Phase 5 – DX: CLI generator
// Usage: node scripts/generate-module.mjs <entity-name>
//   or:  pnpm generate <entity-name>
//
// Examples:
//   node scripts/generate-module.mjs products
//   node scripts/generate-module.mjs blog_posts
// ============================================================

import fs from 'node:fs';
import path from 'node:path';

const MODULES_DIR = path.resolve('client/src/modules');
const CONFIG_DIR = path.resolve('client/src/config');

function toTitleCase(str) {
  return str
    .split(/[-_]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

function toLabel(str) {
  return str
    .split(/[-_]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

function toCamelCase(str) {
  const parts = str.split(/[-_]/);
  return parts[0] + parts.slice(1).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join('');
}

// ─── Templates ─────────────────────────────────────────────

function generateSchemaTemplate(entity) {
  const titleCase = toTitleCase(entity);
  const label = toLabel(entity);
  return `import type { EntitySchema } from '../core/metadata/schema.types';

// ============================================================
// ${titleCase}Schema – Auto-generated by CLI generator
// Customize fields, validation, relations, permissions as needed
// ============================================================

export const ${titleCase}Schema: EntitySchema = {
  name: '${entity}',
  label: '${label}',
  description: '${label} management',
  icon: '📄',
  primaryKey: 'id',
  displayField: 'name',
  defaultSort: { field: 'id', direction: 'desc' },
  defaultPageSize: 20,
  fields: [
    {
      name: 'id',
      label: 'ID',
      type: 'number',
      isPrimary: true,
      showInList: true,
      showInCreate: false,
      showInEdit: false,
    },
    {
      name: 'name',
      label: 'Name',
      type: 'text',
      showInList: true,
      showInCreate: true,
      showInEdit: true,
      sortable: true,
      filterable: true,
      validation: {
        required: true,
        minLength: 1,
        maxLength: 255,
      },
    },
    {
      name: 'created_at',
      label: 'Created At',
      type: 'datetime',
      showInList: true,
      showInCreate: false,
      showInEdit: false,
      sortable: true,
    },
  ],
  permissions: {
    create: true,
    update: true,
    delete: true,
    export: false,
  },
};
`;
}

function generatePageTemplate(entity) {
  const titleCase = toTitleCase(entity);
  return `import React from 'react';
import { DynamicCrudPage } from '../dynamic-crud/DynamicCrudPage';

// ============================================================
// ${titleCase}Page – Auto-generated by CLI generator
// Uses DynamicCrudPage for config-driven CRUD
// ============================================================

export function ${titleCase}Page() {
  return <DynamicCrudPage entityName="${entity}" />;
}

export default ${titleCase}Page;
`;
}

function generateIndexTemplate(entity) {
  const titleCase = toTitleCase(entity);
  return `export { ${titleCase}Page } from './${titleCase}Page';
export { default } from './${titleCase}Page';
`;
}

// ─── Main ──────────────────────────────────────────────────

const entity = process.argv[2];

if (!entity) {
  console.error(`
╔══════════════════════════════════════════╗
║  Base UI – Module Generator CLI          ║
╚══════════════════════════════════════════╝

Usage: node scripts/generate-module.mjs <entity-name>

Examples:
  node scripts/generate-module.mjs products
  node scripts/generate-module.mjs blog_posts
  node scripts/generate-module.mjs user_roles

This will create:
  - client/src/modules/<entity>/<Entity>Page.tsx
  - client/src/modules/<entity>/index.ts

And optionally:
  - client/src/config/<entity>.schema.ts (if not in schemaRegistry)
`);
  process.exit(1);
}

const entitySlug = entity.toLowerCase().replace(/\s+/g, '_');
const titleCase = toTitleCase(entitySlug);
const moduleDir = path.join(MODULES_DIR, entitySlug.replace(/_/g, '-'));

console.log(`\n🏗️  Generating module for entity: ${entitySlug}`);
console.log(`   Title: ${titleCase}`);
console.log(`   Dir:   ${moduleDir}\n`);

// Create module directory
if (!fs.existsSync(moduleDir)) {
  fs.mkdirSync(moduleDir, { recursive: true });
  console.log(`✅ Created directory: ${moduleDir}`);
} else {
  console.log(`⚠️  Directory already exists: ${moduleDir}`);
}

// Generate page file
const pagePath = path.join(moduleDir, `${titleCase}Page.tsx`);
if (!fs.existsSync(pagePath)) {
  fs.writeFileSync(pagePath, generatePageTemplate(entitySlug));
  console.log(`✅ Created page: ${pagePath}`);
} else {
  console.log(`⚠️  Page already exists: ${pagePath}`);
}

// Generate index file
const indexPath = path.join(moduleDir, 'index.ts');
if (!fs.existsSync(indexPath)) {
  fs.writeFileSync(indexPath, generateIndexTemplate(entitySlug));
  console.log(`✅ Created index: ${indexPath}`);
} else {
  console.log(`⚠️  Index already exists: ${indexPath}`);
}

// Generate schema template if not in registry
const schemaPath = path.join(CONFIG_DIR, `${entitySlug}.schema.ts`);
if (!fs.existsSync(schemaPath)) {
  fs.writeFileSync(schemaPath, generateSchemaTemplate(entitySlug));
  console.log(`✅ Created schema: ${schemaPath}`);
} else {
  console.log(`⚠️  Schema already exists: ${schemaPath}`);
}

console.log(`
╔══════════════════════════════════════════╗
║  🎉 Module generated successfully!       ║
╚══════════════════════════════════════════╝

Next steps:
  1. Edit ${schemaPath}
     → Customize fields, relations, validation
  2. Register in schema.config.ts:
     import { ${titleCase}Schema } from './${entitySlug}.schema';
     // Add to schemaRegistry
  3. Add route in App.tsx:
     const ${titleCase}Page = lazy(() => import('./modules/${entitySlug.replace(/_/g, '-')}'));
     <Route path="${entitySlug.replace(/_/g, '-')}" element={<${titleCase}Page />} />
  4. Add nav item in AdminLayout.tsx
`);
